Repository pedrorivera40/MJOLNIR, pull requests merged in 2020-04, with the labels that each got.

#110 Demented earplug/issue 99
  OdinAPI/auth.py
  OdinAPI/main.py
  OdinAPI/tests/test_8_login.py
Labels: testing

#197 Herbert perez/issue 171
  OdinAPI/handler/baseball_event.py
  OdinAPI/handler/basketball_event.py
  OdinAPI/handler/dao/baseball_event_dao.py
  OdinAPI/handler/dao/basketball_event_dao.py
  OdinAPI/handler/dao/mock_dao.py
  OdinAPI/handler/dao/soccer_event_dao.py
  OdinAPI/handler/dao/volleyball_event_dao.py
  OdinAPI/handler/event_result.py
  OdinAPI/handler/soccer_event.py
  OdinAPI/handler/team.py
  OdinAPI/handler/volleyball_event.py
Labels: Back-End

#201 python formatting check
  OdinAPI/handler/baseball_event.py
  OdinAPI/handler/basketball_event.py
  OdinAPI/handler/dao/baseball_event_dao.py
  OdinAPI/handler/dao/basketball_event_dao.py
  OdinAPI/handler/dao/final_score_dao.py
  OdinAPI/handler/dao/soccer_event_dao.py
  OdinAPI/handler/dao/team_dao.py
  OdinAPI/handler/dao/volleyball_event_dao.py
  OdinAPI/handler/event_result.py
  OdinAPI/handler/soccer_event.py
  OdinAPI/handler/team.py
  OdinAPI/handler/volleyball_event.py
Labels: Back-End

#206 Herbert perez/issue 189
  FreyaWebsite/pages/equipo/_id/index.vue
  FreyaWebsite/pages/resultados/_id/index.vue
  LokiDashboard/pages/equipo/_id/index.vue
  LokiDashboard/pages/resultados/_id/crear/index.vue
  LokiDashboard/pages/resultados/_id/equipo/crear/index.vue
  LokiDashboard/pages/resultados/_id/equipo/editar/index.vue
  LokiDashboard/pages/resultados/_id/index.vue
  LokiDashboard/pages/resultados/_id/individual/crear/index.vue
  LokiDashboard/pages/resultados/_id/individual/editar/index.vue
  LokiDashboard/pages/resultados/_id/puntuacion/crear/index.vue
  LokiDashboard/pages/resultados/_id/puntuacion/editar/index.vue
  OdinAPI/handler/dao/team_dao.py
Labels: Front-End

#221 Herbert perez/issue 180
  FreyaWebsite/pages/equipo/_id/index.vue
  FreyaWebsite/pages/resultados/_id/index.vue
  FreyaWebsite/store/results/actions.js
  FreyaWebsite/store/results/getters.js
  FreyaWebsite/store/results/mutations.js
  FreyaWebsite/store/results/state.js
  FreyaWebsite/store/teams/actions.js
  FreyaWebsite/store/teams/getters.js
  FreyaWebsite/store/teams/mutations.js
  FreyaWebsite/store/teams/state.js
  LokiDashboard/pages/equipo/_id/index.vue
  LokiDashboard/pages/resultados/_id/individual/editar/index.vue
  LokiDashboard/store/results/actions.js
  LokiDashboard/store/results/getters.js
  LokiDashboard/store/results/mutations.js
  LokiDashboard/store/results/state.js
  LokiDashboard/store/teams/actions.js
  LokiDashboard/store/teams/getters.js
  LokiDashboard/store/teams/mutations.js
  LokiDashboard/store/teams/state.js
  OdinAPI/handler/baseball_event.py
  OdinAPI/handler/basketball_event.py
  OdinAPI/handler/event_result.py
  OdinAPI/handler/soccer_event.py
  OdinAPI/handler/volleyball_event.py
Labels: Back-End, Front-End, Integration
